:scheduler:
  :schedule:
    late_notifier:
      cron: '0 0 * * * *'   
      class: LateNotifierJob
      :schedule:
    reminder:
      cron: '0 0 * * * *'   
      class: ReminderJob
      :schedule:
    shelf_update:
      cron: '0 0 * * * *'   
      class: ShefUpdateJob
       